### ISSUE TITLE
Bug: Speakers List Does Not Appear on Homepage

### ISSUE THREAD

**Issue by PamelaJohn** [ProgressiveCoders/DemocratizingDemocracy#8]
I added two additional speakers, bios and logos but the speakers list does not appear on the Homepage.

**Comment by jpb5013** [comment]
Was able to fix this one, I believe. As you're adding a speak, you also have to add them to a speaker category. 

![image](https://user-images.githubusercontent.com/11953835/36355226-4a468b32-14ae-11e8-8219-12ad441fcafd.png)

I also updated the Number of speakers on the Homepage Speaker panel 

![image](https://user-images.githubusercontent.com/11953835/36355253-8c6b7fcc-14ae-11e8-8044-f7a52961d866.png)
